services:
  react:
    container_name: react
    build: ./code
    image: nutrify/frontend
    volumes:
      - react-volume:/var/www/html
    networks:
      - nutrify-network

  nginx:
    container_name: nginx
    build: ./nginx
    image: nutrify/nginx
    networks:
      - nutrify-network
    ports:
      - 80:80
    volumes:
      - react-volume:/var/www/html
    depends_on:
      - react

networks:
  nutrify-network:
    name: nutrify-network
    external: true

volumes:
  react-volume:


